name: Build Docker image and Push to Docker Hub.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Build the Docker image
      run: docker build . -t unrealgdev/reseda-mesh:latest --build-arg db_key=${{ secrets.DATABASE_URL }} --build-arg mesh_key=${{ secrets.MESH_KEY }} --build-arg cloudflare_key=${{ secrets.CLOUDFLARE_KEY }} --build-arg cert=${{ secrets.CERTIFICATE }}  --build-arg key=${{ secrets.KEY }}
    -
      name: Push the Docker image
      run: docker push unrealgdev/reseda-mesh:latest
